{"name": "test_max", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6 == 5", "trace": "def test_max():\n        values = (2, 3, 1, 4, 6)\n        val = max(values)\n>       assert val == 5\nE       assert 6 == 5\n\nmax_test.py:37: AssertionError"}, "start": 1687834636893, "stop": 1687834636893, "uuid": "6e456fdf-d3d2-4045-928b-578e09a6786a", "historyId": "a74ada0f6b29f1a1ff0ab9aab766a24d", "testCaseId": "353c02300d259eb292116b06affe674a", "fullName": "src.max_test#test_max", "labels": [{"name": "parentSuite", "value": "src"}, {"name": "suite", "value": "max_test"}, {"name": "host", "value": "DESKTOP-HO1Q1SV"}, {"name": "thread", "value": "7600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.max_test"}]}